name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

        **Before submitting:** Check if the issue exists in the latest version.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have checked the latest version of the documentation
          required: true
        - label: I have searched existing documentation issues
          required: true

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: Which documentation has the issue?
      options:
        - README.md (main module)
        - Example documentation (basic/advanced/provisioner/etc.)
        - CONTRIBUTING.md
        - SECURITY.md
        - SUPPORT.md
        - CHANGELOG.md
        - Code comments/inline documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      placeholder: |
        - File: README.md
        - Section: "Usage Examples"
        - Line: 150
        - Or URL: https://github.com/.../README.md#section
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect/wrong information
        - Outdated information
        - Missing information
        - Unclear/confusing explanation
        - Broken link
        - Typo/grammar
        - Code example doesn't work
        - Missing example
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: Quote the current documentation that has the issue
      placeholder: |
        Current docs say:
        ```
        "Step 1: Configure the module..."
        ```
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong
      description: Explain what's wrong with the current documentation
      placeholder: |
        This is incorrect because...
        This is confusing because...
        This is missing...
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Suggested improvement:
        ```
        "Step 1: First, ensure you have... Then configure the module..."
        ```

        Or: Add a new section explaining...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - This affects users who...
        - Related to issue #123
        - I tried this and got confused because...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help fix this?
      options:
        - label: I am willing to submit a pull request to fix this documentation
          required: false
