name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input.

        **Before submitting:** Please search existing feature requests to avoid duplicates.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have checked the roadmap in MATURITY_ASSESSMENT.md
          required: true
        - label: This feature aligns with the module's scope (Proxmox LXC)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: I would like the module to support...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, when I try to... I cannot...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I need this feature because...
        Example scenario: When deploying to production...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        The module should provide a new variable:

        ```hcl
        new_feature_option = "value"
        ```

        This would allow users to...
    validations:
      required: true

  - type: textarea
    id: example_usage
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      render: hcl
      placeholder: |
        module "lxc" {
          source = "..."

          # New feature example
          new_feature_enabled = true
          new_feature_config = {
            option1 = "value1"
            option2 = "value2"
          }
        }
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: |
        - Alternative 1: Use external script...
        - Alternative 2: Configure manually...
        - Why these don't work: ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for you?
      options:
        - Critical - Blocking my use case
        - High - Very important for my workflow
        - Medium - Would significantly improve experience
        - Low - Nice to have
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What type of feature is this?
      options:
        - New variable/input option
        - New output value
        - New example
        - Enhanced validation
        - Documentation improvement
        - CI/CD enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      placeholder: |
        - Yes, this would require changing...
        - No, this is backward compatible
        - Unknown
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots
      placeholder: |
        - Similar feature in other modules: [link]
        - Related discussion: #123
        - Screenshot: [attach]
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this?
      options:
        - label: I am willing to submit a pull request to implement this feature
          required: false
        - label: I can help test this feature
          required: false
        - label: I can help write documentation for this feature
          required: false
